# BUILD STAGE
FROM node:current-alpine AS build-stage
WORKDIR /app
COPY package*.json /app
RUN npm ci --silent
COPY . /app
ENV NODE_ENV production
RUN npm run build

# PRODUCTION STAGE
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]