version: "3.8"
services:
  client:
    build: ./client
    depends_on:
      - api
      - websocket
    ports:
      - 80:80

  api:
    build: ./api
    ports:
      - 5000:80
    environment:
      MONGO_URI: mongodb://db/visarch-api
      JWT_SECRET: ${JWT_SECRET}  
    volumes:
      - app_public:/app/public

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - visarch:/data/db

  websocket:
    build: ./websocket
    ports:
      - 5001:80
volumes:
  app_public:
    driver: local
  visarch: