services:
  client:
    image: visarch-client:latest
    ports:
      - 3000:80
  api:
    image: visarch-api:latest
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}
      MONGO_URI: mongodb://db/visarch
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
    volumes:
      - app_files:/app/files

  websocket:
    image: visarch-websocket:latest
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}

  db:
    image: mongo:4.0-xenial
    volumes:
      - visarch:/data/db

volumes:
  app_files:
    driver: local
  visarch: