version: "3.8"
services:
  client:
    build: ./client
    depends_on:
      - api
      - websocket
    ports:
      - 80:80
    environment:
      NODE_ENV: production

  api:
    build: ./server/api
    ports:
      - 5000:80
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}
      MONGO_URI: mongodb://db/visarch-api
      JWT_SECRET: ${JWT_SECRET}  
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
    volumes:
      - app_files:/app/files

  websocket:
    build: ./server/websocket
    ports:
      - 5001:80
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - visarch:/data/db

volumes:
  app_files:
    driver: local
  visarch: