version: "3.8"
services:
  client:
    image: visarch-client:latest
    ports:
      - 3000:80
    environment:
      NODE_ENV: production

  api:
    image: visarch-api:latest
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}
      MONGO_URI: mongodb://db/visarch
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
    volumes:
      - app_files:/app/files

  websocket:
    image: visarch-websocket:latest
    ports:
      - 5001:5001
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - visarch:/data/db

volumes:
  app_files:
    driver: local
  visarch: