services:
  client:
    build: ./client
    ports:
      - 3000:80

  api:
    build: ./server/api
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db/visarch
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
    volumes:
      - app_files:/app/files

  websocket:
    build: ./server/websocket
    ports:
      - 5001:5001
    environment:
      NODE_ENV: development

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - visarch:/data/db

volumes:
  app_files:
    driver: local
  visarch: