name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/visarch_client:latest
      -
        name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: ./server/api
          file: ./server/api/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/visarch_api:latest
      -
        name: Build and push websocket image
        uses: docker/build-push-action@v5
        with:
          context: ./server/websocket
          file: ./server/websocket/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/visarch_websocket:latest
